server:
  port: 9090
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-security-keycloak
            client-secret: PVhBNnl3Qg02AmyfjJDPS40kfSu02KPb
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/realm-dev
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm-dev